export const projects = [
  {
    id: "esthetic-insights",
    title: "Esthetic Insights",
    image: "/img17.jpeg",
    year: 2025,
    desc: "Data-driven design analytics to optimize your visual identity.",
    industry: "Design",
    subIndustry: "Analytics",
    deliverables: ["Web design", "Data visualization"],
    completed: "February 2026",
    fundingStage: "Series A",
    backedBy: "ANTLER",
    backedByLogo: "ANTLER",
    about: "Esthetic Insights is focused on helping brands create and optimize beauty, skincare, and haircare products using data-driven design analytics. However, they faced challenges in effectively integrating AI into their product ecosystem and digital presence.",
    images: ["/img2.jpeg", "/img3.jpeg"],
    next: "anthill",
    prev: "pulp",
  },
  {
    id: "anthill",
    title: "Anthill",
    image: "/img16.jpeg",
    year: 2026,
    desc: "The AI Operating System for Venture Capital — pitch intelligence, diligence, portfolio, and LP reporting.",
    industry: "AI",
    subIndustry: "B2B SaaS",
    deliverables: [
      "Pitch deck analysis",
      "Portfolio management",
      "VC workflows automation",
      "LP reports generation",
    ],
    status: "In Dev",
    backedBy: "Anthill Ventures",
    backedByLogo: "Anthill Ventures",
    about: "Anthill is the AI Operating System built for Venture Capital. It reads and scores pitch decks, automates due diligence, monitors portfolio performance, surfaces market intelligence, and generates LP reports — so your team spends less time on process and more time on conviction.",
    images: ["/img5.jpeg", "/img6.jpeg"],
    next: "pulp",
    prev: "esthetic-insights",
  },
  {
    id: "pulp",
    title: "Pulp",
    image: "/img5.jpeg",
    year: 2024,
    desc: "A creative storytelling platform for the next generation of writers.",
    industry: "Creative",
    subIndustry: "Publishing",
    deliverables: ["Web design", "Brand identity"],
    completed: "January 2026",
    fundingStage: "Pre-Seed",
    backedBy: "Y Combinator",
    backedByLogo: "Y",
    about: "Pulp is a creative storytelling platform designed to empower the next generation of writers with collaborative tools and AI-enhanced narrative structures.",
    images: ["/img8.jpeg", "/img9.jpeg"],
    next: "esthetic-insights",
    prev: "anthill",
  },
];
