export const projects = [
  {
    id: "pulp",
    title: "Pulp",
    image: "/projects/assets/img1.jpg",
    year: 2024,
    desc: "A creative storytelling platform for the next generation of writers.",
    industry: "Creative",
    subIndustry: "Publishing",
    deliverables: ["Web design", "Brand identity"],
    completed: "January 2026",
    fundingStage: "Pre-Seed",
    backedBy: "Y Combinator",
    backedByLogo: "Y",
    about: "Pulp is a creative storytelling platform designed to empower the next generation of writers with collaborative tools and AI-enhanced narrative structures.",
    images: ["/projects/assets/img1.jpg"],
    next: "esthetic-insights",
    prev: "anthill",
  },
  {
    id: "esthetic-insights",
    title: "Esthetic Insights",
    image: "/projects/assets/img2.jpg",
    year: 2025,
    desc: "Data-driven design analytics to optimize your visual identity.",
    industry: "Design",
    subIndustry: "Analytics",
    deliverables: ["Web design", "Data visualization"],
    completed: "February 2026",
    fundingStage: "Series A",
    backedBy: "ANTLER",
    backedByLogo: "ANTLER",
    about: "Esthetic Insights is focused on helping brands create and optimize beauty, skincare, and haircare products using data-driven design analytics.",
    images: ["/projects/assets/img2.jpg"],
    next: "anthill",
    prev: "pulp",
  },
  {
    id: "anthill",
    title: "Anthill",
    image: "/projects/assets/img3.jpg",
    year: 2026,
    desc: "The AI Operating System for Venture Capital.",
    industry: "AI",
    subIndustry: "B2B SaaS",
    deliverables: ["Pitch analysis", "Portfolio management"],
    status: "In Dev",
    backedBy: "Anthill Ventures",
    backedByLogo: "Anthill Ventures",
    about: "Anthill is the AI Operating System built for Venture Capital.",
    images: ["/projects/assets/img3.jpg"],
    next: "volery",
    prev: "esthetic-insights",
  },
  {
    id: "volery",
    title: "Volery",
    image: "/projects/assets/img4.jpg",
    year: 2024,
    desc: "Aviation software reimagined.",
    industry: "Aviation",
    subIndustry: "SaaS",
    deliverables: ["Web application", "UI/UX"],
    status: "Live",
    backedBy: "Techstars",
    backedByLogo: "Techstars",
    about: "Volery aims to reimagine the aviation software industry, creating simple, high-impact design systems.",
    images: ["/projects/assets/img4.jpg"],
    next: "alpha",
    prev: "anthill",
  },
  {
    id: "alpha",
    title: "Alpha",
    image: "/projects/assets/img5.jpg",
    year: 2025,
    desc: "Web3 infrastructure and smart contracts.",
    industry: "Web3",
    subIndustry: "Infrastructure",
    deliverables: ["Smart contract", "Frontend"],
    status: "Completed",
    backedBy: "Polygon",
    backedByLogo: "Polygon",
    about: "Alpha provides robust, scalable Web3 infrastructure focusing on highly optimized smart contracts.",
    images: ["/projects/assets/img5.jpg"],
    next: "jay",
    prev: "volery",
  },
  {
    id: "jay",
    title: "Jay",
    image: "/projects/assets/img6.jpg",
    year: 2026,
    desc: "A personalized AI assistant for your daily workflows.",
    industry: "AI",
    subIndustry: "Consumer",
    deliverables: ["Mobile app", "Branding"],
    status: "Beta",
    backedBy: "Sequoia",
    backedByLogo: "Sequoia",
    about: "Jay is an ultimate personalized AI companion designed to handle all daily redundant routines natively.",
    images: ["/projects/assets/img6.jpg"],
    next: "pulp",
    prev: "alpha",
  }
];
