export const projects = [
  {
    id: "pulp",
    title: "Pulp",
    image: "/Logos/img5.jpeg",
    year: 2024,
    desc: "A creative storytelling platform for the next generation of writers.",
    industry: "Creative",
    subIndustry: "Publishing",
    deliverables: ["Web design", "Brand identity"],
    completed: "January 2026",
    fundingStage: "Pre-Seed",
    backedBy: "Y Combinator",
    backedByLogo: "Y",
    about: "Pulp is a creative storytelling platform designed to empower the next generation of writers with collaborative tools and AI-enhanced narrative structures.",
    images: ["/projects/pulp/hero.png", "/projects/pulp/cosmic-dew.png"],
    next: "esthetic-insights",
    prev: "anthill",
  },
  {
    id: "esthetic-insights",
    title: "Esthetic Insights",
    image: "/Logos/img16.jpeg",
    year: 2025,
    desc: "Data-driven design analytics to optimize your visual identity.",
    industry: "Design",
    subIndustry: "Analytics",
    deliverables: ["Web design", "Data visualization"],
    completed: "February 2026",
    fundingStage: "Series A",
    backedBy: "ANTLER",
    backedByLogo: "ANTLER",
    about: "Esthetic Insights is focused on helping brands create and optimize beauty, skincare, and haircare products using data-driven design analytics.",
    images: ["/projects/esthetic-insights/gallery-1.png", "/projects/esthetic-insights/gallery-2.png"],
    next: "anthill",
    prev: "pulp",
  },
  {
    id: "anthill",
    title: "Anthill",
    image: "/Logos/img17.jpeg",
    year: 2026,
    desc: "The AI Operating System for Venture Capital.",
    industry: "AI",
    subIndustry: "B2B SaaS",
    deliverables: ["Pitch analysis", "Portfolio management"],
    status: "In Dev",
    backedBy: "Anthill Ventures",
    backedByLogo: "Anthill Ventures",
    about: "Anthill is the AI Operating System built for Venture Capital.",
    images: ["/projects/anthill/hero.png", "/projects/anthill/gallery-2.png"],
    next: "pulp",
    prev: "esthetic-insights",
  },
];
